name: Build images

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - Dockerfile
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build Image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          tags: hieupth/nginx:latest